#abc=("today your class will stop after few days ago strted my class")
#print(abc)
#y=(abc.find("class"))
#print(y)
#print(abc[y:50])

#abc=("today your class will stop after few days ago strted my class")
#y=(abc.find("class"))
#print(abc[:y])
abc=("I like to play guiter and i am huge fan of sungha jung and he play very good guiter")
y=(abc.find("guitar"))
print(y)
abc=("I like to play guiter and i am huge fan of sungha jung and he play very good guiter")
print(abc.find("guitar")+5)

#abc=("I like to play guiter and i am huge fan of sungha jung and he play very good guiter")
#xyz=(abc.find("play"))
#tuv=(abc.find("play",xyz+1))
#print(tuv)
#print("\dfnfdijn")
#abc=("I like to play guiter and i am huge fan of sungha jung and he play very good guiter")
#xyz=(abc.find("play"))
#tuv=(abc.find("play",xyz+1))
#print(tuv)
#print(abc[tuv:])
#print(y)
